apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      - system:nodes
      rolearn: arn:aws:iam::749979325296:role/eksctl-my-project-nodegroup-ng-15-NodeInstanceRole-G2WORMUZUGRK
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::749979325296:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-30T16:53:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1413"
  uid: 5ec36e79-a751-4bf8-8c49-1463f077a5ca
